#!/bin/sh
NUMLINES=$1
LOGFILE=$2
shift
shift

if [-z "$NUMLINES" ]; then
    echo Error: a parameter indicating the number of lines is required.
    exit 1
fi

if [-z "$LOGFILE" ]; then
    echo Error: a parameter indicating the log file is required.
    exit 1
fi

exec /usr/bin/tail -$NUMLINES $LOGFILE
