#!/bin/bash

# Adapted from create_template_postgis-debian.sh by Shimon Rura
# Mon Jun 13 22:15:49 EDT 2011

DBNAME=$1

if [ -z "$DBNAME" ]; then
    echo Error: a database name parameter is required.
    exit 1
fi

# For Ubuntu 8.x and 9.x releases.
if [ -d "/usr/share/postgresql-8.3-postgis" ]
then
    POSTGIS_SQL_PATH=/usr/share/postgresql-8.3-postgis
    POSTGIS_SQL=lwpostgis.sql
fi

# For Ubuntu 10.04
if [ -d "/usr/share/postgresql/8.4/contrib" ]
then
    POSTGIS_SQL_PATH=/usr/share/postgresql/8.4/contrib
    POSTGIS_SQL=postgis.sql
fi

# For Ubuntu 10.10 (with PostGIS 1.5)
if [ -d "/usr/share/postgresql/8.4/contrib/postgis-1.5" ]
then
    POSTGIS_SQL_PATH=/usr/share/postgresql/8.4/contrib/postgis-1.5
    POSTGIS_SQL=postgis.sql
    GEOGRAPHY=1
else
    GEOGRAPHY=0
fi

# createdb -E UTF8 template_postgis && \
# psql -d postgres -c "UPDATE pg_database SET datistemplate='true' WHERE datname='template_postgis';" && \
sudo -u postgres createlang -d $DBNAME plpgsql && \
sudo -u postgres psql -d $DBNAME -f $POSTGIS_SQL_PATH/$POSTGIS_SQL && \
sudo -u postgres psql -d $DBNAME -f $POSTGIS_SQL_PATH/spatial_ref_sys.sql && \
sudo -u postgres psql -d $DBNAME -c "GRANT ALL ON geometry_columns TO PUBLIC;" && \
sudo -u postgres psql -d $DBNAME -c "GRANT ALL ON spatial_ref_sys TO PUBLIC;"

if ((GEOGRAPHY))
then
    sudo -u postgres psql -d $DBNAME -c "GRANT ALL ON geography_columns TO PUBLIC;"
fi
